# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  publish-on-pypi:
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Update version.py with release tag
      env:
        RELEASE_TAG: ${{ github.event.release.tag_name }}
      run: |
        python .github/scripts/update_version.py --version $RELEASE_TAG

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1